### ISSUE TITLE
Consistent error with MacOS

### ISSUE THREAD

**Issue by amunn** [MartinScharrer/texdef#3]
Hi Martin, I originally raised this issue on the Sourceforge repo, but I guess it didn't get transferred. For a while now, on MacOS, `texdef` throws an error on every invocation, even though it still seems to work.  

Example:

```
Sagui:~ alan$ latexdef \underline
Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/^\\\@protected\@testopt { <-- HERE ?\\.*? }? *(\\\\.*?) / at /usr/local/bin/latexdef line 391.
Unescaped left brace in regex is passed through in regex; marked by <-- HERE in m/^\\\@testopt { <-- HERE ?(\\.*?) }?/ at /usr/local/bin/latexdef line 394.

\underline:
macro:->\protect \underline  


\underline :
\long macro:#1->\relax \ifmmode \@@underline {#1}\else $\@@underline {\hbox {#1}}\m@th $\relax \fi 

```

If I invoke `texdef` with `perl` directly, the error disappears.

```
Sagui:~ alan$ perl latexdef \underline

\underline:
macro:->\protect \underline  


\underline :
\long macro:#1->\relax \ifmmode \@@underline {#1}\else $\@@underline {\hbox {#1}}\m@th $\relax \fi 
```

**Comment by MartinScharrer** [comment]
This problem was fixed already. Maybe you have an older version of `(la)texdef` installed. Maybe two different versions, one with the OS package manager and one in the manually installed TeX distribution?

Try both calls with the `--version` argument and compare. Check if you have the latest version.

Also check if both calls use the same version of Perl. Older Perl do not bring this warning. Newest versions throw an error on it.

**Comment by amunn** [comment]
Indeed I had a version from 2012 installed `/usr/local/bin`.  Thanks!  Everything works now.
